spring.application.name=processor-service

server.port=${SERVER_PORT:3001}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:processor_db}
spring.datasource.username=${DB_USER:processor_user}
spring.datasource.password=${DB_PASSWORD:processor_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

accounts.service.url=${ACCOUNTS_SERVICE_URL:http://localhost:3000}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always