spring.application.name=processor-service

server.port=${PROCESSOR_SERVICE_PORT:3001}

spring.datasource.url=jdbc:postgresql://${PROCESSOR_DB_HOST:localhost}:${PROCESSOR_DB_PORT_LOCAL:5435}/${PROCESSOR_DB_NAME:processor_db}
spring.datasource.username=${PROCESSOR_DB_USER:processor_user}
spring.datasource.password=${PROCESSOR_DB_PASSWORD:processor_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

accounts.service.url=${ACCOUNTS_SERVICE_URL:http://localhost:3000}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always