server.port=8083
spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/officespace_db
spring.datasource.username=admin_alpha
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Una llave secreta cualquiera para firmar los tokens (En prod sería más larga y segura)
jwt.secret=MySuperSecretKeyForHackathonAlphaCorp2026!