# Puerto distintivo para auth-service
server.port=8080

# JWT Configuration
# ¡CAMBIAR EN PRODUCCIÓN!
jwt.secret.key=pT1dKz0jY8vG6VbZYvR8WeO/AwD+Jm1Hk8M0xUeVh4U=
# 1 hora en milisegundos
jwt.expiration.ms=3600000
jwt.issuer=corporativoalpha.com

# OpenAPI (Swagger) Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html