# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8081
spring.application.name=catalog-service

# ===============================
# CONEXIÓN A POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/officespace_db
spring.datasource.username=admin_alpha
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# Usamos 'validate' para que Java solo compruebe que las tablas que hiciste en DBeaver existan
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar logs de SQL en la consola (súper útil para el hackathon)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true