spring.application.name=catalog-service
server.port=8081

# Conexión a la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/officespace_db
spring.datasource.username=officespace_user
spring.datasource.password=officespace_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Logs de seguridad
logging.level.org.springframework.security=INFO