version: '3.8'

services:
  db:
    image: postgres:15
    container_name: officespace_db
    environment:
      POSTGRES_DB: officespace_db
      POSTGRES_USER: officespace_user
      POSTGRES_PASSWORD: officespace_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  auth-service:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_MS: 3600000
      JWT_ISSUER: corporativoalpha.com

  catalog-service:
    build: ./catalog-service
    container_name: catalog_service
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/officespace_db
      SPRING_DATASOURCE_USERNAME: officespace_user
      SPRING_DATASOURCE_PASSWORD: officespace_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

volumes:
  postgres_data:
