spring.application.name=booking-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/officespace_db
spring.datasource.username=officespace_user
spring.datasource.password=officespace_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=OfficeSpaceSecretKeyForHackathon2026ChangeInProduction
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/api-docs
springdoc.api-docs.path=/v3/api-docs

logging.level.org.springframework.security=INFO
