services:
  postgres:
    image: postgres:15
    container_name: officespace-postgres
    restart: always
    environment:
      POSTGRES_DB: ${OFFICESPACE_DB_NAME}
      POSTGRES_USER: ${OFFICESPACE_DB_USER}
      POSTGRES_PASSWORD: ${OFFICESPACE_DB_PASSWORD}
    ports:
      - "${OFFICESPACE_DB_PORT}:5432"
    volumes:
      - officespace_postgres_data:/var/lib/postgresql/data
      - ./shared-infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  officespace_postgres_data: