spring.application.name=catalogService
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/officeSpace
spring.datasource.username=postgres
spring.datasource.password=Davfeb26022002+
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:S3cr3tK3yP4r4H4ck4th0n2026MustBeAtLeast256BitsLong!}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
