version: '3.8'

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: officespace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - ./shared-infra/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  catalog-service:
    build: ./catalog-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: secret123
      DB_NAME: officespace
      DB_PORT: 5432
      JWT_SECRET: clave_super_secreta_officespace_2026
      TZ: America/Mexico_City
    depends_on:
      - db

  booking-service:
    build: ./booking-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: secret123
      DB_NAME: officespace
      DB_PORT: 5432
      JWT_SECRET: clave_super_secreta_officespace_2026
      TZ: America/Mexico_City
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - catalog-service
      - booking-service

volumes:
  postgres_data:

