spring.application.name=authService
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/officeSpace
spring.datasource.username=postgres
spring.datasource.password=Davfeb26022002+
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:S3cr3tK3yP4r4H4ck4th0n2026MustBeAtLeast256BitsLong!}
jwt.expiration=${JWT_EXPIRATION:86400000}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
