// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Indica si el servicio está operativo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salud"
                ],
                "summary": "Sonda de salud",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SaludResponse"
                        }
                    }
                }
            }
        },
        "/resources": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos"
                ],
                "summary": "Listar recursos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Recurso"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos"
                ],
                "summary": "Crear recurso",
                "parameters": [
                    {
                        "description": "Datos del recurso",
                        "name": "recurso",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RecursoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Recurso"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        },
        "/resources/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos"
                ],
                "summary": "Actualizar recurso",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del recurso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del recurso",
                        "name": "recurso",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RecursoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Recurso"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recursos"
                ],
                "summary": "Eliminar recurso",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del recurso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Sin contenido"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        },
        "/spaces": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista los espacios. Soporta filtros por tipo y capacidad mínima, aplicados en la consulta.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "espacios"
                ],
                "summary": "Listar espacios",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtra por tipo (SALA o DESK)",
                        "name": "tipo",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Capacidad mínima",
                        "name": "capacidad_min",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Espacio"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "espacios"
                ],
                "summary": "Crear espacio",
                "parameters": [
                    {
                        "description": "Datos del espacio",
                        "name": "espacio",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EspacioRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Espacio"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        },
        "/spaces/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "espacios"
                ],
                "summary": "Obtener espacio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del espacio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Espacio"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "espacios"
                ],
                "summary": "Actualizar espacio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del espacio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del espacio",
                        "name": "espacio",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EspacioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Espacio"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "espacios"
                ],
                "summary": "Eliminar espacio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del espacio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Sin contenido"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apperror.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apperror.AppError": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "mensaje": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "handlers.SaludResponse": {
            "type": "object",
            "properties": {
                "servicio": {
                    "type": "string",
                    "example": "catalog-service"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "models.Espacio": {
            "type": "object",
            "properties": {
                "capacidad": {
                    "type": "integer",
                    "example": 8
                },
                "creado_en": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nombre": {
                    "type": "string",
                    "example": "Sala Monterrey"
                },
                "piso": {
                    "type": "string",
                    "example": "Piso 1"
                },
                "recursos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Recurso"
                    }
                },
                "tipo": {
                    "type": "string",
                    "example": "SALA"
                }
            }
        },
        "models.EspacioRequest": {
            "type": "object",
            "properties": {
                "capacidad": {
                    "type": "integer",
                    "example": 8
                },
                "nombre": {
                    "type": "string",
                    "example": "Sala Monterrey"
                },
                "piso": {
                    "type": "string",
                    "example": "Piso 1"
                },
                "recurso_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "tipo": {
                    "type": "string",
                    "example": "SALA"
                }
            }
        },
        "models.Recurso": {
            "type": "object",
            "properties": {
                "creado_en": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nombre": {
                    "type": "string",
                    "example": "Proyector"
                }
            }
        },
        "models.RecursoRequest": {
            "type": "object",
            "properties": {
                "nombre": {
                    "type": "string",
                    "example": "Proyector"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Escribe: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OfficeSpace — Catalog Service",
	Description:      "Gestión de espacios (CRUD) y búsqueda con filtros. Escritura solo para ADMINISTRADOR.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
