spring.application.name=accounts-service

server.port=${ACCOUNTS_SERVICE_PORT:3000}

spring.datasource.url=jdbc:postgresql://${ACCOUNTS_DB_HOST:localhost}:${ACCOUNTS_DB_PORT_LOCAL:5434}/${ACCOUNTS_DB_NAME:accounts_db}
spring.datasource.username=${ACCOUNTS_DB_USER:accounts_user}
spring.datasource.password=${ACCOUNTS_DB_PASSWORD:accounts_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always